dolar/dolar/urls.py
from django.contrib import admin
from django.urls import path, include

# from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls'), name='home'),
]

# handler404 = 'views.error404'

dolar/home/urls.py
from django.urls import path

from . import views

app_name = 'quotes'  ## allows for quotes:detail or quotes:archive reference
urlpatterns = [
    path('home/', views.IndexView.as_view(), name='index'),
    path('archive/', views.ArchiveView.as_view(), name='archive'),
    path('archive/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('login', views.LoginInterfaceView.as_view(), name='login'),
    path('logout/', views.LogoutInterfaceView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('', views.WelcomeView.as_view(), name='welcome'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('password/', views.PasswordView.as_view(), name='password'),
    path('history_bna/', views.BNAHistory.as_view(), name='history_bna'),
    path('history_bbva/', views.BBVAHistory.as_view(), name='history_bbva'),
    path('history_blue/', views.BlueHistory.as_view(), name='history_blue'),
    path('history_santander/', views.SantanderHistory.as_view(), name='history_santander'),
    path('history_patagonia/', views.PatagoniaHistory.as_view(), name='history_patagonia'),
    path('history_cop/', views.COPHistory.as_view(), name='history_cop'),
]

dolar/home/models.py
from time import strftime
from django.db import models
from django.utils.timesince import timesince
from datetime import datetime

class Cotizacion(models.Model):
    datetime = models.DateTimeField()
    currency = models.CharField(max_length=50, blank=False, null=False)
    name = models.CharField(max_length=50, blank=False, null=False)
    buy = models.FloatField()
    sell = models.FloatField()
    other = models.FloatField()

    def __str__(self):
        return f"{self.currency.upper()} {self.name.upper()} {datetime.strftime(self.datetime, '%Y-%m-%d %H:%M:%S')}"

    # def time_diff(self):
    #     return timesince(self.datetime, datetime.now()).split(",")[0]

    def date_month(self):
        return datetime.strftime("%m-%d", self.datetime)

    def time_relative(self):
        days = (datetime.now().date() - self.datetime.date()).days
        hours = (datetime.now().hour - self.datetime.hour)
        minutes = (datetime.now().minute - self.datetime.minute)
        if days == 0:
            # difference = 'Hoy'
            if hours == 1:
                difference = f'Hace 1 h'
            elif hours > 1:
                difference = f'Hace {hours} hs'
            else:
                difference = f'Hace {minutes} min'
        elif days == 1:
            difference = 'Ayer'
        elif days > 1:
            difference = f'Hace {days} días'
        return difference

    class Meta:
        managed = False
        db_table = 'cotizacion'

dolar/home/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms

class EditProfileForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.HiddenInput(), required = False) # hides the field

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class PasswordForm(PasswordChangeForm):
    old_password = forms.CharField(label='Current password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password2 = forms.CharField(label='Repeat new password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

dolar/home/views.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect

from datetime import datetime, timedelta

from django.views.generic import TemplateView

from .models import Cotizacion
from .forms import EditProfileForm, PasswordForm


class SignupView(CreateView):
    form_class = UserCreationForm
    template_name = 'home/signup.html'
    success_url = 'home/'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('home/')
        return super().get(request, *args, **kwargs)


class ProfileView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = EditProfileForm
    template_name = 'home/profile.html'
    success_url = '/profile'
    login_url = 'quotes:login'
    success_message = 'Profile settings have been updated'

    def get_object(self):
        return self.request.user


class PasswordView(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    form_class = PasswordForm
    template_name='home/password.html'
    success_url = '/password'
    success_message = 'Successfully updated password'


class IndexView(LoginRequiredMixin, ListView):
    template_name = 'home/index.html'
    context_object_name = 'latest_quote_list'
    login_url = 'quotes:login'

    def get_latest_ars(self):
        return [
            Cotizacion.objects.order_by('-datetime').filter(name='blue')[:2],
            Cotizacion.objects.order_by('-datetime').filter(name='bna')[:2],
            Cotizacion.objects.order_by('-datetime').filter(name='bbva')[:2],
            Cotizacion.objects.order_by('-datetime').filter(name='santander')[:2],
            Cotizacion.objects.order_by('-datetime').filter(name='patagonia')[:2],
        ]

    def get_latest_cop(self):
        return [
            Cotizacion.objects.order_by('-datetime').filter(currency='cop')[:2],
        ]

    def get_queryset(self):
        """Return the last five published values."""
        return {"ars": self.get_latest_ars(), "cop": self.get_latest_cop()}


class ArchiveView(LoginRequiredMixin, ListView):
    template_name = 'home/archive.html'
    context_object_name = 'quote_list'
    login_url = 'quotes:login'

    def get_last_entries(self, currency, name, days_back=15):
        results = []
        days = 0
        while days < days_back:
            given_date = datetime.now().date() - timedelta(days=days)
            cotiz = Cotizacion.objects.order_by('-datetime').filter(currency=currency).filter(name=name).filter(datetime__date = given_date)
            if len(cotiz) > 0:
                results.append(cotiz[0])
            days += 1
        return results

    # def get_ars(self):
    #     return [
    #         Cotizacion.objects.order_by('-datetime').filter(name='blue')[:50],
    #         Cotizacion.objects.order_by('-datetime').filter(name='bna')[:50],
    #         Cotizacion.objects.order_by('-datetime').filter(name='bbva')[:50],
    #         Cotizacion.objects.order_by('-datetime').filter(name='santander')[:50],
    #         Cotizacion.objects.order_by('-datetime').filter(name='patagonia')[:50],
    #     ]

    def get_ars(self):
        blue = self.get_last_entries('ars', 'blue')
        bna = self.get_last_entries('ars', 'bna')
        bbva = self.get_last_entries('ars', 'bbva')
        santander = self.get_last_entries('ars', 'santander')
        patagonia = self.get_last_entries('ars', 'patagonia')
        return [blue, bna, bbva, santander, patagonia]
        # return [blue]

    def get_cop(self):
        return [
            Cotizacion.objects.order_by('-datetime').filter(currency='cop')[:50],
        ]


    def get_queryset(self):
        """Return the last five published values."""
        return {"ars": self.get_ars(), "cop": self.get_cop()}


class HistoryView(LoginRequiredMixin, ListView):
    template_name = 'home/history.html'
    context_object_name = 'quote_list'
    login_url = 'quotes:login'

    def __init__(self, currency, name):
        self.currency = currency
        self.name = name

    def get_last_entries(self, currency, name, days_back=15):
        results = []
        days = 0
        while days < days_back:
            given_date = datetime.now().date() - timedelta(days=days)
            cotiz = Cotizacion.objects.order_by('-datetime').filter(currency=currency).filter(name=name).filter(datetime__date = given_date)
            if len(cotiz) > 0:
                results.append(cotiz[0])
            days += 1
        return results

    def get_values(self):
        values = self.get_last_entries(self.currency, self.name)
        return values

    def get_queryset(self):
        """Return the last value for earch day."""
        return {"values": self.get_values()}


class BNAHistory(HistoryView):
    def __init__(self, currency='ars', name='bna'):
        super().__init__(currency, name)


class BBVAHistory(HistoryView):
    def __init__(self, currency='ars', name='bbva'):
        super().__init__(currency, name)


class BlueHistory(HistoryView):
    def __init__(self, currency='ars', name='blue'):
        super().__init__(currency, name)


class SantanderHistory(HistoryView):
    def __init__(self, currency='ars', name='santander'):
        super().__init__(currency, name)


class PatagoniaHistory(HistoryView):
    def __init__(self, currency='ars', name='patagonia'):
        super().__init__(currency, name)


class COPHistory(HistoryView):
    def __init__(self, currency='cop', name='generic'):
        super().__init__(currency, name)


class DetailView(LoginRequiredMixin, DetailView):
    model = Cotizacion
    template_name = 'home/detail.html'
    context_object_name = 'quote'
    login_url = 'quotes:login'


class LoginInterfaceView(LoginView):
    template_name = 'home/login.html'


class LogoutInterfaceView(LogoutView):
    template_name = 'home/logout.html'


class WelcomeView(LoginView):
    template_name = 'home/welcome.html'

    def get(self, request, *args, **kwargs):     # overriding this method redirects to indicated website when authenticated
        if self.request.user.is_authenticated:
            return redirect('home/')
        return super().get(request, *args, **kwargs)

dolar/home/templates/home/archive.html
{% extends 'home/base.html' %}

{% block title %} Archive {% endblock %}

{% block content %}

<div class="my-5 container">

{% if quote_list %}

    {% for bank in quote_list.ars %}
        <div class="table-responsive">
            <table class="table table-striped table-hover">
            <thead>
                <tr>
                <th scope="col">{{ bank.0.name | slice:4 | upper }}</th>
                <th scope="col">Compra</th>
                <th scope="col">Venta</th>
                </tr>
            </thead>
            <tbody>
    
            {% for quote in bank %}
                <tr>
                {% comment %} <td>{{ quote.datetime | date:"Y-m-d H:i:s" }}</td> {% endcomment %}
                <td>{{ quote.datetime | date:"m-d" }}</td>
                <td>{{ quote.buy | floatformat:2 }}</td>
                <td>{{ quote.sell | floatformat:2 }}</td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
        </div>
    {% endfor %}
{% else %}
    <p>No quotes are available.</p>
{% endif %}

{% for bank in quote_list.cop %}
<div class="table-responsive">
    <table class="table table-striped table-hover">
    <thead>
        <tr>
        <th scope="col">{% if bank.0.name != 'generic' %}{{ bank.0.name | upper }}{% else %}COP{% endif %}</th>
        <th scope="col">Compra</th>
        <th scope="col">Venta</th>
        </tr>
    </thead>
    <tbody>

    {% for quote in bank %}
        <tr>
        {% comment %} <td>{{ quote.datetime | date:"Y-m-d H:i:s" }}</td> {% endcomment %}
        <td>{{ quote.datetime | date:"m-d" }}</td>
        <td>{{ quote.buy | floatformat:2 }}</td>
        <td>{{ quote.sell | floatformat:2 }}</td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
</div>
{% endfor %}


</div>

{% endblock %}

dolar/home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>"Cotización"</title>
        <meta charset="utf-8">
        <link rel="shortcut icon" href="{% static '' %}home/images/favicon/favicon.ico"/>
        <link rel="icon" type="image/png" sizes="192x192" href="{% static '' %}home/images/favicon/favicon-192x192.png">
        <link rel="icon" type="image/png" sizes="256x256" href="{% static '' %}home/images/favicon/favicon-256x256.png">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static '' %}home/images/favicon/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static '' %}home/images/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static '' %}home/images/favicon/favicon-16x16.png">
        <link rel="manifest" href="{% static '' %}home/images/favicon/site.webmanifest">        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>

<body>
    <nav class='navbar navbar-dark bg-dark'>
        <div class='ms-auto'>
            {% if user.is_authenticated %}
                <a href="{% url 'quotes:index' %}" class="btn btn-outline-light me-1">Home</a>
                <a href="{% url 'quotes:archive' %}" class="btn btn-outline-light me-4">Archive</a>
                <a href="{% url 'quotes:profile' %}" class="btn btn-outline-light me-1">{{ user.first_name }}</a>
                <a href="{% url 'quotes:logout' %}" class="btn btn-danger me-1">Logout</a>
            {% else %}
                <a href="{% url 'quotes:login' %}" class="btn btn-success me-1">Login</a>
                <a href="{% url 'quotes:signup' %}" class="btn btn-outline-light me-1">Signup</a>
            {% endif %}
        </div>

    </nav>

    <div class="my-5 container" align="center"><h1>{% block title %} Title {% endblock %}</h1></div>

    <div class="my-5 container">
    
        {% block content %}

        {% endblock %}
    
    </div>

    </div>

</body>
</html>

dolar/home/templates/home/chart.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %} Charts {% endblock %}

{% block content %}

    <canvas id="myChart" width="500" height="400"></canvas>

    <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
    <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
    <script type="text/javascript">
        $.get('{% url "quotes:line_chart_json" %}', function(data) {
            var ctx = $("#myChart").get(0).getContext("2d");
            new Chart(ctx, {
                type: 'line', data: data
            });
        });
    </script>

{% endblock %}

dolar/home/templates/home/detail.html
{% extends 'home/base.html' %}

{% block title %} {{ quote.currency | upper }} {{ quote.name | title }} {% endblock %}

{% block content %}

<ul>
    <li>Fecha: {{ quote.datetime }}</li>
    <li>Compra: {{ quote.buy }}</li>
    <li>Venta: {{ quote.sell }}</li>
    <li>Tarjeta: {{ quote.other }}</li>
</ul>

{% endblock %}

dolar/home/templates/home/history.html
{% extends 'home/base.html' %}

{% block title %} Histórico 
    {% if quote_list.values.0.currency == 'cop' %}
        COP
    {% elif quote_list.values.0.name|length <= 4 %}
        {{ quote_list.values.0.name|upper }}
    {% else %}
        {{ quote_list.values.0.name|title }}
    {% endif %} 
{% endblock %}

{% block content %}

<div class="my-5 container">

{% if quote_list %}

        <div class="table-responsive">
            <table class="table table-striped table-hover">
            <thead>
                <tr>
                <th class="d-none d-md-block" scope="col">Fecha</th>
                <th scope="col">Compra</th>
                <th scope="col">Venta</th>
                <th scope="col">Update</th>
                </tr>
            </thead>
            <tbody>
    
            {% for quote in quote_list.values %}
                <tr>
                <td class="d-none d-md-block">{{ quote.datetime | date:"Y-m-d H:i:s" }}</td>
                <td>{{ quote.buy | floatformat:2 }}</td>
                <td>{{ quote.sell | floatformat:2 }}</td>
                <td>{{ quote.time_relative }}</td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
        </div>
{% else %}
    <p>No quotes are available.</p>
{% endif %}

</div>

{% endblock %}

dolar/home/templates/home/index.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %} Cotizaciones {% endblock %}

{% block content %}

    {% if latest_quote_list.ars %}

            <div class="table-responsive">
                <table class="table table-striped table-hover">
                <thead>
                    <tr>
                    <th scope="col">ARS 🇦🇷</th>
                    <th scope="col">Compra</th>
                    <th scope="col">Venta</th>
                    <th scope="col">Tarjeta</th>
                    <th scope="col" class="d-none d-md-block">Update</th>
                    </tr>
                </thead>
                <tbody>
                {% for quote in latest_quote_list.ars %}
                    <tr>
                    <td><img src="{% static '' %}home/images/{{ quote.0.name }}.png" width="20" height="20"> <a class="link-dark text-decoration-none" href="/history_{{quote.0.name}}"><strong>{{ quote.0.name | slice:4 | upper }}</strong></a></td>
                    <td>{{ quote.0.buy | floatformat:2 }} {% if quote.0.buy > quote.1.buy or quote.1.buy == None %}<font color="red">&#9650;</font>{% else %}<font color="green">&#9660;</font>{% endif %}</td>
                    <td>{{ quote.0.sell | floatformat:2 }} {% if quote.0.sell > quote.1.sell or quote.1.sell == None %}<font color="red">&#9650;</font>{% else %}<font color="green">&#9660;</font>{% endif %}</td>
                    <td>{% if quote.0.other > 0 %}{{ quote.0.other | floatformat:2 }} {% if quote.0.other > quote.1.other or quote.1.other == None %}<font color="red">&#9650;</font>{% else %}<font color="green">&#9660;</font>{% endif %}{% endif %}</td>
                    <td class="d-none d-md-block">{{ quote.0.time_relative }}</td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
            </div>
    {% else %}
        <p>No quotes are available.</p>
    {% endif %}

    <br><br>

    {% if latest_quote_list.cop %}
            <div class="table-responsive">
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">COP 🇨🇴</th>
                    <th scope="col">Compra</th>
                    <th scope="col">Venta</th>
                    <th scope="col">TRM</th>
                    <th scope="col" class="d-none d-md-block">Update</th>
                    </tr>
                </thead>
                <tbody>
                {% for quote in latest_quote_list.cop %}
                    <tr>
                    <td><img src="{% static '' %}home/images/blue.png" width="20" height="20"> <a class="link-dark text-decoration-none" href="/history_{{quote.0.currency}}"><strong>{{ quote.0.name | slice:3 | upper }}</strong></a></td>
                    <td>{{ quote.0.buy | floatformat:2 }} {% if quote.0.buy > quote.1.buy or quote.1.buy == None %}<font color="red">&#9650;</font>{% else %}<font color="green">&#9660;</font>{% endif %}</td>
                    <td>{{ quote.0.sell | floatformat:2 }} {% if quote.0.sell > quote.1.sell or quote.1.sell == None %}<font color="red">&#9650;</font>{% else %}<font color="green">&#9660;</font>{% endif %}</td>
                    <td>{% if quote.0.other > 0 %}{{ quote.0.other | floatformat:2 }} {% if quote.0.other > quote.1.other or quote.1.other == None %}<font color="red">&#9650;</font>{% else %}<font color="green">&#9660;</font>{% endif %}{% endif %}</td>
                    <td class="d-none d-md-block">{{ quote.0.time_relative }}</td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
            </div>
    {% else %}
        <p>No quotes are available.</p>
    {% endif %}

{% endblock %}

dolar/home/templates/home/login.html
{% extends 'home/base.html' %}

{% block title %} Log in {% endblock %}

{% block content %}

<div class="my-5 container" align="center">

<form method="post"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-secondary">

</div>

{% endblock %}

dolar/home/templates/home/logout.html
{% extends 'home/base.html' %}

{% block title %} Logged out successfully {% endblock %}

{% block content %}

<div class="my-5 container" align="center">

    <h3>Come back soon!</h3>

</div>

{% endblock %}

dolar/home/templates/home/password.html
{% extends 'home/base.html' %}

{% block title %} Change password {% endblock %}

{% block content %}

<div class="my-5 container">

<form method="post"> {% csrf_token %}
    {% if messages %}
    <div class="alert alert-success">
        {% for m in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</li>
        {% endfor %}
    </div>
    {% endif %}

    {{ form.as_p }}
    <input type="submit" class="btn btn-secondary" value='Change password'>

</div>

{% endblock %}

dolar/home/templates/home/profile.html
{% extends 'home/base.html' %}

{% block title %} Profile {% endblock %}

{% block content %}

<div class="my-5 container">

    <div class="my-1 container" align='center'>
    {% if user.is_superuser %}
        <input type="button" class="btn btn-secondary btn-warning" onclick="location.href='/admin'" value="Admin portal"></input><br><br>
    {% endif %}
    </div>

<form method="post" style='text-align: left; margin: 0 auto; width: auto' > {% csrf_token %}
    {% if messages %}
    <div class="alert alert-success">
        {% for m in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</li>
        {% endfor %}
    </div>
    {% endif %}
    
        {{ form.as_p }}
        <input type="submit" class="btn btn-secondary btn-success" value='Update'>
        <input type="button" class="btn btn-secondary" value="Reset" id="resetBtn" onClick="this.form.reset()" />
        <input type="button" class="btn btn-secondary" onclick="location.href='/password'" value="Change Password"></input>
</div>

{% endblock %}

dolar/home/templates/home/signup.html
{% extends 'home/base.html' %}

{% block title %} Sign up {% endblock %}

{% block content %}

<div class="my-5 container">

<form method="post" style='text-align: left; margin: 0 auto; width: 600px' > {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-secondary" name='Submit'>

</div>

{% endblock %}

dolar/home/templates/home/welcome.html
{% extends 'home/base.html' %}

{% block title %} Welcome {% endblock %}

{% block content %}

{% endblock %}